#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor DP-0 -d I II III IV V
# bspc monitor DP-2 -d VI VII VIII IX X

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10

bspc monitor DP-0 -d 1 2 3 4 5 
bspc monitor DP-2 -d 6 7 8 9 10
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config leaf_monocle         true
bspc config single_monocle         true
bspc config focus_follows_pointer true

bspc config focused_border_color '#a3be8c'

bspc rule -a Franz desktop='^10'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nm-applet &
nitrogen --restore &
$HOME/.config/polybar/launch.sh & 
redshift &

# Set cursor
# xsetroot -cursor_name left_ptr &
